// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCpU41WOwc7SHe8gY6VefYVC8kpLoayXw',
    appId: '1:892872803918:web:61ac09e2b0a4bb05ec251f',
    messagingSenderId: '892872803918',
    projectId: 'intune-19e26',
    authDomain: 'intune-19e26.firebaseapp.com',
    databaseURL: 'https://intune-19e26-default-rtdb.firebaseio.com',
    storageBucket: 'intune-19e26.appspot.com',
    measurementId: 'G-V6D5EDZG5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDzSTR_b-EclJTiUfgQo-zkY3n5uoxb-Y',
    appId: '1:892872803918:android:85e6e99890a560c5ec251f',
    messagingSenderId: '892872803918',
    projectId: 'intune-19e26',
    databaseURL: 'https://intune-19e26-default-rtdb.firebaseio.com',
    storageBucket: 'intune-19e26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvX1DZJ_IgigCjEsSaa7SRPEveaUIujz0',
    appId: '1:892872803918:ios:378b143530217e06ec251f',
    messagingSenderId: '892872803918',
    projectId: 'intune-19e26',
    databaseURL: 'https://intune-19e26-default-rtdb.firebaseio.com',
    storageBucket: 'intune-19e26.appspot.com',
    iosClientId: '892872803918-vf5pvka68djgtgk3tm708h4ie13rj6d7.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstone-project-intune',
  );
}
